let zapatillas = [
    {
        _id:"z1",
        descripcion: "Nike Air Max 270 to Chuck Taylors",
        talla: "42",
        color: "c1",
        cantidad: 1,
        precio: 150.00,
        img: "img/shoes1.png",
    },
    {
        _id:"z2",
        descripcion: "Zapatillas Jaguar Oficial Deportiva",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 250.00,
        img: "img/shoes2.png",
    },
    {
        _id:"z3",
        descripcion: "Zapatillas Entrenamiento Nike Air Max",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 350.00,
        img: "img/shoes3.png",
    },
    {
        _id:"z4",
        descripcion: "Zapatillas Nike Air Max",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 164.00,
        img: "img/shoes4.png",
    },
    {
        _id:"z5",
        descripcion: "Zapatillas Nike Tenis",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 210.00,
        img: "img/shoes5.png",
    },
    {
        _id:"z6",
        descripcion: "Zapatillas de Skate Air Force",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 350.00,
        img: "img/shoes6.png",
    },
    {
        _id:"z7",
        descripcion: "Nike Air Max 270 to Chuck Taylors",
        talla: "42",
        color: "c1",
        cantidad: 1,
        precio: 150.00,
        img: "img/shoes1.png",
    },
    {
        _id:"z8",
        descripcion: "Zapatillas Jaguar Oficial Deportiva",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 250.00,
        img: "img/shoes2.png",
    },
    {
        _id:"z9",
        descripcion: "Zapatillas Entrenamiento Nike Air Max",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 350.00,
        img: "img/shoes3.png",
    },
    {
        _id:"z10",
        descripcion: "Zapatillas Nike Air Max",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 164.00,
        img: "img/shoes4.png",
    },
    {
        _id:"z11",
        descripcion: "Zapatillas Nike Tenis",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 210.00,
        img: "img/shoes5.png",
    },
    {
        _id:"z12",
        descripcion: "Zapatillas de Skate Air Force",
        talla: "40",
        color: "c2",
        cantidad: 1,
        precio: 350.00,
        img: "img/shoes6.png",
    },

]

export { zapatillas };